[package]
name = "fibo_rust"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[lib]
name = "fibo_rust"
crate-type = ["cdylib", "lib"]

[dependencies.pyo3]
version = "0.22.5"
features = ["abi3-py310"]
